### ISSUE TITLE
PSTH for init

### ISSUE THREAD

**Issue by zova137** [ethierlab/doric_fiberphotometry#1]
@siamakhaz I need two different PSTH graph: 
Both with success and failure in the same graph but in one of them time zero is the time of init (we already have it in the current version)
and the other graph with time zero is equal to the time of occurrence of success/fail.

**Comment by siamakhaz** [comment]
Feature added on this [commit](https://github.com/ethierlab/doric_fiberphotometry/commit/9c934ff9ede42d55659bb72f2a4334fc24e1b898#diff-b32a5b23dba022493e581d90284921db54fd6dd49c8b7c7a27739cfa43aeeabb)
@zova137 Just remember to use one of the Jupiter boxes
